language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script: ./gradlew testMockDebugUnitTest
